builders:
  keyBuilder:
    import: "package:code_generator/builder.dart"
    builder_factories: ["keyBuilder"]
    build_extensions: {".dart": [".keys.g.part"]}
    auto_apply: dependents
    build_to: source
    # applies_builders: ["source_gen|combining_builder"]
  objectModelBuilder:
    import: "package:code_generator/builder.dart"
    builder_factories: ["objectModelBuilder"]
    build_extensions: {".dart": [".object_model.dart"]}
    auto_apply: dependents
    build_to: source

